services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/db
      - REDIS_HOST=redis
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:8.2
    restart: always
    volumes:
      - mongo_data:/var/lib/mongodb/data
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  mongo_data:
  redis_data: